@startuml
' DEFINICIONES
actor Cliente as cliente
actor :Cliente VIP: as vip
(Reservar vuelo) as vuelo
(Reservar asientos) as asiento

' RELACIONES
cliente -- vuelo
vip -- asiento
vip --|> cliente
@enduml