@startuml
' DEFINICIONES
:Ciudadano: as ciudadano
:Ciudadano extranjero: as extranjero
(Registrar entrada) as registrar
(Tomar huellas) as huellas

' RELACIONES
left to right direction
ciudadano -- registrar
extranjero -- huellas
extranjero --|> ciudadano
huellas ..> registrar

@enduml