@startuml
' DEFINICIONES
usecase sacar as "Sacar dinero
 --
 + solicitud hecha"
 usecase "retener tarjeta" as retener

' RELACIONES
 sacar <.. retener: <<Extend>>
note on link
 Description
 --
 condicion:
  {historia sospechosa}
 punto de extensión:
  solicitud hecha"
end note

@enduml